updated to include a runner flag which allows remote selenium to be used
alexnaish/scholar-runner pull request #7
Opened 2016-09-21 14:26 UTC by nwc1991

We needed to extend scholar-runner so that we can run it over a selenium server within a Docker environment.

We added a runner option where you can specific where to run the tests e.g. local, remote or broswerstack, we left the broswerstack flag in just so that we don't create a braking change, and added the code to run with a remote selenium server

2016-09-21 22:58 UTC, alexnaish commented
I'm not going to accept this just yet, I think it should be refactored to reduce an overlap in options and functionality. Essentially all the browserstack option does is set up a remote selenium session with the browserstack selenium location pre-specified - with a few extra options admittedly but they could be moved into the config file.

For this to be merged this needs:

- Consolidation of the CLI options / functionality.
 - Remove the --browserstack option in favour of the runner parameter.
- `connectToRemoteSeleniumAndRunTests` and `setupBrowserStackAndRunTests` are essentially the same function duplicated.
- Possibly move the selenium configuration out of the function into the config file and refactor the previously mentioned functions into one `setupRemoteSessionAndRunTests` (for example)

2016-09-22 12:52 UTC, nowarkdev requested changes
The options object should be cleaner, the user and key settings shouldn't be hardcoded to be the BROWSERSTACK process variables. These should just be set to the relevant config fields. Since the config variable is a JS file, end users can choose to use process variables where required. 

Additionally, on `lib/runner.js:66` options.browserstackLocal will never be set as the option has been removed so this needs to be fixed.

2016-09-22 16:08 UTC, nowarkdev commented on lib/runner.js
> +        "user": config.browserstack ? config.browserstack.user : '',
How about the below, as it isn't directly related to browserstack. Any remote selenium server can have a username and password associated with it.

"user": config.user,
"key": config.key

2016-09-22 16:09 UTC, nowarkdev commented on lib/runner.js
>      let bsOptions = {
Could this not be done with something along the lines of an `Object.assign(standardOptions, config)`?

2016-09-22 16:09 UTC, nowarkdev commented on README.md
> +            key: 'browserstack-automation-key',
See below comment around fields.

2016-09-22 16:09 UTC, nowarkdev requested changes

2016-09-26 08:30 UTC, alexnaish commented
Looks good from the diff, will checkout and give it a run through.

2016-09-28 21:34 UTC, merged